
name: Pipeline Java Spring Boot

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-e-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurar JDK 17
      
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribuition: 'temurin'

    - name: Dar permissão ao gradlew
      run: chmod +x gradlew

